package com.bush.pharmacy_web_app.repository.entity.order.state;

public enum OrderEvent {
    PAYMENT_TIME_EXPIRED,
    POST_PAYMENT_METHOD_SELECTED,
    PAYMENT_RECEIVED,

    DECORATED_ORDER,
    SHIPPED_ORDER,
    DELIVERED_ORDER,
    OPERATOR_COMPLETES_ORDER,
    OPERATOR_RETURNS_ORDER,

    ORDER_CANCELLED_BY_USER,
    SELLER_ISSUE,
    WAREHOUSE_ISSUE,
    LOGISTIC_ISSUE,

    RETURN_REQUESTED_BY_USER,
    RETURN_APPROVED,
    RETURN_DISAPPROVED,
    RETURN_TIME_EXPIRED,
    ORDER_RETURNED_BY_USER,
    SHIPPED_RETURN,
    DELIVERED_RETURN
}
